In [23]:
import numpy as np
from numpy.linalg import inv
from fractions import Fraction as frac
import math

***Mô hình cân bằng thị trường:***(Mô hình cung cầu)

Hàm cung $S=S(p)$

Hàm cầu $D=D(p)$

Cân bàng thị trường khi $D(\overline{p})=S(\overline{p})$

***Mô hình đầu tư:***

$l$ : số vốn đầu tư 

$r$: lãi suất 

Dạng đơn giản: $l= a+br$ trong đó $a>0, b<0$ 

***Mô hình vào ra***


*   Hộp đen kinh tế vĩ mô
*   Hàm sản xuất 

      $y = f(L_1, L_2, K, T)$

      $y$: tăng trưởng kinh tế

      $L_1$: đất đai

      $K$: vốn 

      $T$: công nghệ

*   Hàm sản xuất Cobb-Douglass

      $A=a.K^\alpha.L^\beta $ ($a>0$)

      $\alpha+\beta=1$: Nhịp tăng trưởng sản phẩm = nhịp tăng trưởng của nhân tố sản xuất

      $\alpha+\beta>1$: Nhịp tăng trưởng sản phẩm > nhịp tăng trưởng của nhân tố sản xuất
      
      $\alpha+\beta<1$: Nhịp tăng trưởng sản phẩm < nhịp tăng trưởng của nhân tố sản xuất

# Dạng hiện vật

In [2]:
Q = np.array([[20,10,8],
             [10,10,16],
             [10,10,8]])
SPCC = np.array([62,14,12])
SL = np.array([100,50,40])
LĐ = np.array([30,20,10])
alpha = Q/SL
theta = inv(np.eye(len(SPCC))-alpha)
beta = LĐ/SL
print("Ma trận hệ số chi phí trực tiếp dạng hiện vật alpha:\n ",alpha)
print("Ma trận chi phí toàn phần dạng hiện vật theta:\n ",theta)
print("Vecto hệ số sử dụng lao động beta:\n ",beta)

Ma trận hệ số chi phí trực tiếp dạng hiện vật alpha:
  [[0.2 0.2 0.2]
 [0.1 0.2 0.4]
 [0.1 0.2 0.2]]
Ma trận chi phí toàn phần dạng hiện vật theta:
  [[1.38613861 0.4950495  0.59405941]
 [0.2970297  1.53465347 0.84158416]
 [0.24752475 0.44554455 1.53465347]]
Vecto hệ số sử dụng lao động beta:
  [0.3  0.4  0.25]


# Dạng giá trị

In [3]:
X = np.array([[120,120,40],
              [120,120,20],
              [60,80,20]])
SPCC = np.array([320,140,40])
SL = np.array([600,400,200])
YTDVSC = np.array([[0,0,20],
                  [120,20,40],
                  [60,0,20],
                  [60,0,20],
                  [60,60,20]])
G = np.array([20,180,80,80,40])
A = X/SL
B = YTDVSC/SL
C = inv(np.eye(len(SPCC))-A)
vector_chiphi_tp = np.sum(C,axis=0)
deltaX = np.sum(C,axis=1)
index = np.argmax(vector_chiphi_tp)
print("Ma trận hệ số chi phí dạng giá trị A:\n ",A)
print("Ma trận hệ số các yếu tố đầu vào sơ cấp B:\n ",B)
print("Ma trận chi phí toàn phần dạng giá trị C:\n ",C)
print("Vector chi phí toàn phần:\n ",vector_chiphi_tp)
print("Để phát triển sản xuất, cần thúc đẩy ngành:\n ",index+1)
print("DeltaX:\n ",deltaX)

Ma trận hệ số chi phí dạng giá trị A:
  [[0.2 0.3 0.2]
 [0.2 0.3 0.1]
 [0.1 0.2 0.1]]
Ma trận hệ số các yếu tố đầu vào sơ cấp B:
  [[0.   0.   0.1 ]
 [0.2  0.05 0.2 ]
 [0.1  0.   0.1 ]
 [0.1  0.   0.1 ]
 [0.1  0.15 0.1 ]]
Ma trận chi phí toàn phần dạng giá trị C:
  [[1.49144254 0.75794621 0.41564792]
 [0.46454768 1.71149144 0.29339853]
 [0.26894866 0.46454768 1.22249389]]
Vector chi phí toàn phần:
  [2.22493888 2.93398533 1.93154034]
Để phát triển sản xuất, cần thúc đẩy ngành:
  2
DeltaX:
  [2.66503667 2.46943765 1.95599022]


# Tìm ma trận I/O ở năm t+1 (giá trị sản phẩm cuối cùng thay đổi)

In [10]:
A = np.array([[0.2,0.3,0.2],
              [0.4,0.1,0.2],
              [0.1,0.3,0.2]])
B = np.array([[0.04,0,0.025],
            [0.06,0.15,0.1],
            [0.04,0.05,0.075],
            [0.04,0.05,0.05],
            [0.12,0.1,0.15]])
SPCC = np.array([100,40,75])
coef_inc = np.array([0.1,-0.1,0.0]) # Hệ số tăng giảm
SPCC_t_next = SPCC+np.multiply(SPCC,coef_inc)
C = inv(np.eye(len(SPCC))-A)
print("Ma trận chi phí toàn phần dạng giá trị C:\n ",C)
X_t = C@SPCC
print(np.multiply(A,X_t))
# print("Vector giá trị tổng sản lượng của năm t là X_t:\n ",X_t)
# X_t_next = C@SPCC_t_next
# print("Vector giá trị tổng sản lượng của năm t+1 là X_(t+1):\n ",X_t_next)
# x_t_next = np.multiply(A,X_t_next)
# print(x_t_next)
# g_t_next = np.multiply(B,X_t_next)
# print(g_t_next)
# G_t_next = np.sum(g_t_next,axis=1)
# print(G_t_next)

Ma trận chi phí toàn phần dạng giá trị C:
  [[1.71875    0.78125    0.625     ]
 [0.88541667 1.61458333 0.625     ]
 [0.546875   0.703125   1.5625    ]]
[[ 50.  60.  40.]
 [100.  20.  40.]
 [ 25.  60.  40.]]


# Tìm ma trận I/O ở năm t+1 (giá trị tổng sản lượng thay đổi)

In [17]:
A = np.array([[0.2,0.3,0.2],
              [0.4,0.1,0.2],
              [0.1,0.3,0.2]])
B = np.array([[0.04,0,0.025],
            [0.06,0.15,0.1],
            [0.04,0.05,0.075],
            [0.04,0.05,0.05],
            [0.12,0.1,0.15]])
SPCC = np.array([100,40,75])

coef_inc = np.array([0.1,-0.1,0.0]) # Hệ số tăng giảm
C = inv(np.eye(len(SPCC))-A)
print("Ma trận chi phí toàn phần dạng giá trị C:\n ",C)
X_t = C@SPCC
print("Vector giá trị tổng sản lượng của năm t là X_t:\n ",X_t)
X_t_next = X_t+np.multiply(X_t,coef_inc)
print("Vector giá trị tổng sản lượng của năm t+1 là X_(t+1):\n ",X_t_next)
print("Vector giá trị sản phẩm cuối cùng của năm t là X_t:\n ",SPCC)
SPCC_t_next = (np.eye(len(SPCC))-A)@X_t_next
print("Vector giá trị sản phẩm cuối cùng của năm t+1 là X_(t+1):\n ",SPCC_t_next)
x_t_next = np.multiply(A,X_t_next)
print(x_t_next)
g_t_next = np.multiply(B,X_t_next)
print(g_t_next)
G_t_next = np.sum(g_t_next,axis=1)
print(G_t_next)

Ma trận chi phí toàn phần dạng giá trị C:
  [[1.71875    0.78125    0.625     ]
 [0.88541667 1.61458333 0.625     ]
 [0.546875   0.703125   1.5625    ]]
Vector giá trị tổng sản lượng của năm t là X_t:
  [250. 200. 200.]
Vector giá trị tổng sản lượng của năm t+1 là X_(t+1):
  [275. 180. 200.]
Vector giá trị sản phẩm cuối cùng của năm t là X_t:
  [100  40  75]
Vector giá trị sản phẩm cuối cùng của năm t+1 là X_(t+1):
  [126.   12.   78.5]
[[ 55.   54.   40. ]
 [110.   18.   40. ]
 [ 27.5  54.   40. ]]
[[11.   0.   5. ]
 [16.5 27.  20. ]
 [11.   9.  15. ]
 [11.   9.  10. ]
 [33.  18.  30. ]]
[16.  63.5 35.  30.  81. ]


# Mô hình quản lý dự trữ giản đơn
- Tổng chi phí mua hàng cả năm : CQ
- Chi phí bảo quản một đơn vị hàng dự trữ : IC

In [42]:
A = 100 # Chi phí cố định cho mỗi lần đặt hàng
Q = 16000 # Số lượng hàng dự trữ trong 1 năm
T0 = 1 # Thời gian đặt hàng
C = 240 # Gía 1 đơn vị hàng dữ trữ, tính cả phí vận chuyển
I = 0.12# Hệ số chi phí bảo quản

S_star = np.sqrt((2*A*Q)/(I*C)) # Lượng đặt hàng tối ưu cho mỗi lần đặt hàng
print("Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:\n ",S_star)
n_star = Q/S_star # Số lần đặt hàng tối ưu
print("Số lần đặt hàng tối ưu:\n ",n_star)
t_star = 1/n_star # Chu kỳ dự trữ tiêu thụ tối ưu
print("Chu kỳ dự trữ tiêu thụ tối ưu:\n ",t_star)
D_star = np.sqrt(2*A*Q*I*C) # Chi phí dự trữ tối ưu (không kể chi phí mua hàng)
print("Chi phí dự trữ tối ưu (không kể chi phí mua hàng):\n ",D_star)
D_star_overline = np.sqrt(2*A*Q*I*C) + C*Q # Chi phí dự trữ tối ưu (kể cả chi phí mua hàng)
print("Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):\n ",D_star)
Z_star = S_star/2 # Lượng hàng dữ trự trung bình tối ưu trong kho
print("Lượng hàng dữ trự trung bình tối ưu trong kho:\n ",Z_star)
if T0<=t_star:
    Q_star = Q*T0
    print("Đặt hàng khi trong kho còn "+str(Q_star)+" đơn vị hàng")
else:
    m = int(T0/t_star)
    m0 = T0-t_star*m #năm
    Q_star = Q*(T0-t_star*m)
    print("Đặt hàng trước "+str(m)+" chu kỳ khi trong kho còn lại lượng hàng tiêu thụ trong khoảng thời gian "+str(m0)+" năm, tức là trong kho còn lại "+str(Q_star)+" đơn vị hàng")


Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:
  1118.033988749895
Số lần đặt hàng tối ưu:
  107.3312629199899
Chu kỳ dự trữ tiêu thụ tối ưu:
  0.009316949906249124
Chi phí dự trữ tối ưu (không kể chi phí mua hàng):
  32199.378875996972
Lượng hàng dữ trự trung bình tối ưu trong kho:
  559.0169943749474
Đặt hàng trước 107 chu kỳ khi trong kho còn lại lượng hàng tiêu thụ trong khoảng thời gian 0.003086360031343771 năm, tức là trong kho còn lại 370.3632037612525 đơn vị hàng


# Mô hình dữ trự với hàng hóa bổ sung dần

In [39]:
A = 210 # Chi phí cố định cho mỗi lần đặt hàng
Q = 120000 # Nhu cầu một loại hàng hóa trong thời gian T
T0 = 45/365  # Thời gian đặt hàng
C = 140 # Gía 1 đơn vị hàng dữ trữ, tính cả phí vận chuyển
I = 2.5/138 # Hệ số chi phí bảo quản
K = 600000 # Cường độ bổ sung hàng
S_star = np.sqrt((2*A*Q*K)/(I*C*(K-Q))) # Lượng đặt hàng tối ưu cho mỗi lần đặt hàng
print("Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:\n ",S_star)
n_star = Q/S_star # Số lần đặt hàng tối ưu
print("Số lần đặt hàng tối ưu:\n ",n_star)
t_star = 1/n_star # Chu kỳ dự trữ tiêu thụ tối ưu
print("Chu kỳ dự trữ tiêu thụ tối ưu:\n ",t_star)
D_star = np.sqrt((2*A*Q*I*C*(K-Q))/K) # Chi phí dự trữ tối ưu (không kể chi phí mua hàng)
print("Chi phí dự trữ tối ưu (không kể chi phí mua hàng):\n ",D_star)
Z_star = (S_star/2)*(1-(Q/K)) # Lượng hàng dữ trự trung bình tối ưu trong kho
print("Lượng hàng dữ trữ trung bình tối ưu trong kho:\n ",Z_star)
Z_max = (S_star)*(1-(Q/K)) # Lượng hàng dữ trự lớn nhất trong kho
print("Lượng hàng dữ trữ lớn nhất trong kho:\n ",Z_max)
D_star_overline = C*Q + D_star # Chi phí dự trữ tối ưu (kể cả chi phí mua hàng)
print("Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):\n ",D_star_overline)
Q_star = Q*(T0-t_star*int(T0/t_star))
if Q_star<=Z_max:
    print("Đặt hàng khi làm vơi kho, và trong kho còn lại lượng hàng là:\n ",Q_star)
else:
    tmp = (K-Q)*(t_star-(Q_star//Q))
    print("Đặt hàng khi đang làm đầy kho, khi trong kho còn lại lượng hàng là:\n ",tmp)

Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:
  4983.974317750845
Số lần đặt hàng tối ưu:
  24.07717061715384
Chu kỳ dự trữ tiêu thụ tối ưu:
  0.041533119314590375
Chi phí dự trữ tối ưu (không kể chi phí mua hàng):
  10112.411659204612
Lượng hàng dữ trữ trung bình tối ưu trong kho:
  1993.5897271003382
Lượng hàng dữ trữ lớn nhất trong kho:
  3987.1794542006764
Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):
  16810112.411659203
Đặt hàng khi đang làm đầy kho, khi trong kho còn lại lượng hàng là:
  19935.89727100338


In [ ]:
16809797.9589711

# Mô hình 2 mức giá

In [15]:
A = 150 # Chi phí cố định cho mỗi lần đặt hàng
Q = 6000 # Nhu cầu một loại hàng hóa trong thời gian T
T0 = 1/4  # Thời gian đặt hàng
C0 = 45
C1 = 34
S0 = 0
S1 = 1000
I = 0.1 # Hệ số chi phí bảo quản
def val(C,S):
    return A*Q/S + C*Q + I*C*S/2
S1_star = np.sqrt((2*A*Q)/(I*C1))
if S1_star >= S1:
    print("Nghiệm tối ưu là S* = S1* = ",S1_star)
    print("Chi phí dự trữ tối ưu là D* = D(C1,S1*) = ",val(C1,S1_star))
else:
    
    S0_star = np.sqrt((2*A*Q)/(I*C0))
    if val(C0,S0_star)<val(C1,S1):
        #print("in")
        print("Nghiệm tối ưu là S* = S0* = ",S0_star)
        print("Chi phí dự trữ tối ưu là D* = D(C0,S0*) = ",val(C0,S0_star))
    else:
        print("Nghiệm tối ưu là S* = S1 = ",S1)
        print("Chi phí dự trữ tối ưu là D* = D(C1,S1) = ",val(C1,S1))

Nghiệm tối ưu là S* = S1 =  1000
Chi phí dự trữ tối ưu là D* = D(C1,S1) =  206600.0


# Mô hình 3 mức giá

In [13]:
A = 50 # Chi phí cố định cho mỗi lần đặt hàng
Q = 8000 # Nhu cầu một loại hàng hóa trong thời gian T
T0 = 90/365  # Thời gian đặt hàng
C0 = 25
C1 = 24
C2 = 23.5
S0 = 0
S1 = 1000
S2 = 3000
Sopt = 0
I = 0.2 # Hệ số chi phí bảo quản
def val(C,S):
    return A*Q/S + C*Q + I*C*S/2
S2_star = np.sqrt((2*A*Q)/(I*C2))
S1_star = np.sqrt((2*A*Q)/(I*C1))
S0_star = np.sqrt((2*A*Q)/(I*C0))
if S2_star >= S2:
    print("Nghiệm tối ưu là S* = S2* = ",S2_star)
    print("Chi phí dự trữ tối ưu là D* = D(C2,S2*) = ",val(C2,S2_star))
    Sopt = S2_star
elif S1<=S2_star<S2:
    if S1_star>=S1:
        idx = np.argmin([val(C1,S1_star),val(C2,S2)])
        if idx==0:
            print("Nghiệm tối ưu là S* = S1* = ",S1_star)
            print("Chi phí dự trữ tối ưu là D* = D(C1,S1*) = ",val(C1,S1_star))
            Sopt = S1_star
        else:
            print("Nghiệm tối ưu là S* = S2 = ",S2)
            print("Chi phí dự trữ tối ưu là D* = D(C2,S2) = ",val(C2,S2))
            Sopt = S2
    else:    
        idx = np.argmin([val(C0,S0_star),val(C1,S1),val(C2,S2)])
        if idx==0:
            print("Nghiệm tối ưu là S* = S0* = ",S0_star)
            print("Chi phí dự trữ tối ưu là D* = D(C0,S0*) = ",val(C0,S0_star))
            Sopt = S0_star
        elif idx==1:
            print("Nghiệm tối ưu là S* = S1 = ",S1)
            print("Chi phí dự trữ tối ưu là D* = D(C1,S1) = ",val(C1,S1))
            Sopt = S1
        else:
            print("Nghiệm tối ưu là S* = S2 = ",S2)
            print("Chi phí dự trữ tối ưu là D* = D(C2,S2) = ",val(C2,S2))
            Sopt = S2
elif S0<=S2_star<S1:
    idx = np.argmin([val(C0,S0_star),val(C1,S1),val(C2,S2)])
    if idx==0:
        print("Nghiệm tối ưu là S* = S0* = ",S0_star)
        print("Chi phí dự trữ tối ưu là D* = D(C0,S0*) = ",val(C0,S0_star))
        Sopt = S0_star
    elif idx==1:
        print("Nghiệm tối ưu là S* = S1 = ",S1)
        print("Chi phí dự trữ tối ưu là D* = D(C1,S1) = ",val(C1,S1))
        Sopt = S1
    else:
        print("Nghiệm tối ưu là S* = S2 = ",S2)
        print("Chi phí dự trữ tối ưu là D* = D(C2,S2) = ",val(C2,S2))
        Sopt = S2

S_star = Sopt# Lượng đặt hàng tối ưu cho mỗi lần đặt hàng
print("Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:\n ",S_star)
n_star = Q/S_star # Số lần đặt hàng tối ưu
print("Số lần đặt hàng tối ưu:\n ",n_star)
t_star = 1/n_star # Chu kỳ dự trữ tiêu thụ tối ưu
print("Chu kỳ dự trữ tiêu thụ tối ưu:\n ",t_star)
D_star = np.sqrt(2*A*Q*I*C) # Chi phí dự trữ tối ưu (không kể chi phí mua hàng)
print("Chi phí dự trữ tối ưu (không kể chi phí mua hàng):\n ",D_star)
D_star_overline = np.sqrt(2*A*Q*I*C) + C*Q # Chi phí dự trữ tối ưu (kể cả chi phí mua hàng)
print("Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):\n ",D_star)
Z_star = S_star/2 # Lượng hàng dữ trự trung bình tối ưu trong kho
print("Lượng hàng dữ trự trung bình tối ưu trong kho:\n ",Z_star)
if T0<=t_star:
    Q_star = Q*T0
    print("Đặt hàng khi trong kho còn "+str(Q_star)+" đơn vị hàng")
else:
    m = int(T0/t_star)
    m0 = T0-t_star*m #năm
    Q_star = Q*(T0-t_star*m)
    print("Đặt hàng trước "+str(m)+" chu kỳ khi trong kho còn lại lượng hàng tiêu thụ trong khoảng thời gian "+str(m0)+" năm, tức là trong kho còn lại "+str(Q_star)+" đơn vị hàng")

Nghiệm tối ưu là S* = S1 =  1000
Chi phí dự trữ tối ưu là D* = D(C1,S1) =  194800.0
Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:
  1000
Số lần đặt hàng tối ưu:
  8.0
Chu kỳ dự trữ tiêu thụ tối ưu:
  0.125
Chi phí dự trữ tối ưu (không kể chi phí mua hàng):
  [[480.         219.089023   200.        ]
 [280.         447.2135955  160.        ]
 [200.         211.66010489 430.81318457]]
Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):
  [[480.         219.089023   200.        ]
 [280.         447.2135955  160.        ]
 [200.         211.66010489 430.81318457]]
Lượng hàng dữ trự trung bình tối ưu trong kho:
  500.0
Đặt hàng trước 1 chu kỳ khi trong kho còn lại lượng hàng tiêu thụ trong khoảng thời gian 0.12157534246575341 năm, tức là trong kho còn lại 972.6027397260273 đơn vị hàng


# Mô hình n mức giá

In [21]:
A = 100 # Chi phí cố định cho mỗi lần đặt hàng
Q = 10000 # Nhu cầu một loại hàng hóa trong thời gian T
T0 = 90/365  # Thời gian đặt hàng
C = 140 # Gía 1 đơn vị hàng dữ trữ, tính cả phí vận chuyển (dành cho mô hình dự trữ)
# C0 = 25
# C1 = 24
# C2 = 23.5
C_ = [25,24,23.5]
S_ = [0,1000,5000]
# S0 = 0
# S1 = 1000
# S2 = 3000
I = 0.2
def QL3(Q,A,C,I,S):
    Sopt = 0
    i=len(C)-1
    S.append(10000000000)
    A = np.array(A)
    C = np.array(C)
    D=A*Q/S[i]+C[i]*Q+I*C[i]*S[i]/2
    Ssao= S[i]
    while True:
        i=i-1
        if(i<0):
            break
        Si=np.sqrt(2*A*Q/(I*C[i]))
        if (S[i]<=Si)*(Si<S[i+1])==1:
            break
        Di=A*Q/S[i]+C[i]*Q+I*C[i]*S[i]/2
        D=np.vstack((np.array(Di),np.array(D)))
        Ssao=np.vstack((np.array(S[i]),np.array(Ssao)))
        
    Di=A*Q/Si+C[i]*Q+I*C[i]*Si/2
    D=np.vstack((np.array(Di),np.array(D)))
    Ssao=np.vstack((np.array(Si),np.array(Ssao)))

    for j in range(0,len(D)):
        if D[j]==np.min(D):
            
            if j==0:
                print("S* = S",i,"* = ",Ssao[j][0])
                print("D* = D(C",i,",S",i,"*) = ",D[j][0])
                Sopt = Ssao[j][0]
                # print("i = ",i)
            else:
                print("S* = S",j," = ",Ssao[j][0])
                print("D* = D(C",j,",S",j,") = ",D[j][0])
                Sopt = Ssao[j][0]
    return Sopt
Sopt = QL3(Q,A,C_,I,S_)

# # Mô hình giản đơn
# S_star = Sopt# Lượng đặt hàng tối ưu cho mỗi lần đặt hàng
# print("Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:\n ",S_star)
# n_star = Q/S_star # Số lần đặt hàng tối ưu
# print("Số lần đặt hàng tối ưu:\n ",n_star)
# t_star = 1/n_star # Chu kỳ dự trữ tiêu thụ tối ưu
# print("Chu kỳ dự trữ tiêu thụ tối ưu:\n ",t_star)
# D_star = np.sqrt(2*A*Q*I*C) # Chi phí dự trữ tối ưu (không kể chi phí mua hàng)
# print("Chi phí dự trữ tối ưu (không kể chi phí mua hàng):\n ",D_star)
# D_star_overline = np.sqrt(2*A*Q*I*C) + C*Q # Chi phí dự trữ tối ưu (kể cả chi phí mua hàng)
# print("Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):\n ",D_star)
# Z_star = S_star/2 # Lượng hàng dữ trự trung bình tối ưu trong kho
# print("Lượng hàng dữ trự trung bình tối ưu trong kho:\n ",Z_star)
# if T0<=t_star:
#     Q_star = Q*T0
#     print("Đặt hàng khi trong kho còn "+str(Q_star)+" đơn vị hàng")
# else:
#     m = int(T0/t_star)
#     m0 = T0-t_star*m #năm
#     Q_star = Q*(T0-t_star*m)
#     print("Đặt hàng trước "+str(m)+" chu kỳ khi trong kho còn lại lượng hàng tiêu thụ trong khoảng thời gian "+str(m0)+" năm, tức là trong kho còn lại "+str(Q_star)+" đơn vị hàng")

# print('Mô hình với hàng hóa bổ sung dần')
# # Mô hình với hàng hóa bổ sung dần
# K = 16000 # Cường độ bổ sung hàng
# S_star = Sopt # Lượng đặt hàng tối ưu cho mỗi lần đặt hàng
# print("Lượng đặt hàng tối ưu cho mỗi lần đặt hàng:\n ",S_star)
# n_star = Q/S_star # Số lần đặt hàng tối ưu
# print("Số lần đặt hàng tối ưu:\n ",n_star)
# t_star = 1/n_star # Chu kỳ dự trữ tiêu thụ tối ưu
# print("Chu kỳ dự trữ tiêu thụ tối ưu:\n ",t_star)
# D_star = np.sqrt((2*A*Q*I*C*(K-Q))/K) # Chi phí dự trữ tối ưu (không kể chi phí mua hàng)
# print("Chi phí dự trữ tối ưu (không kể chi phí mua hàng):\n ",D_star)
# Z_star = (S_star/2)*(1-(Q/K)) # Lượng hàng dữ trự trung bình tối ưu trong kho
# print("Lượng hàng dữ trữ trung bình tối ưu trong kho:\n ",Z_star)
# Z_max = (S_star)*(1-(Q/K)) # Lượng hàng dữ trự lớn nhất trong kho
# print("Lượng hàng dữ trữ lớn nhất trong kho:\n ",Z_max)
# D_star_overline = C*Q + D_star # Chi phí dự trữ tối ưu (kể cả chi phí mua hàng)
# print("Chi phí dự trữ tối ưu (kể cả chi phí mua hàng):\n ",D_star_overline)
# Q_star = Q*(T0-t_star*int(T0/t_star))
# if Q_star<=Z_max:
#     print("Đặt hàng khi làm vơi kho, và trong kho còn lại lượng hàng là:\n ",Q_star)
# else:
#     tmp = (K-Q)*(t_star-(Q_star//Q))
#     print("Đặt hàng khi đang làm đầy kho, khi trong kho còn lại lượng hàng là:\n ",tmp)

S* = S 1  =  1000.0
D* = D(C 1 ,S 1 ) =  243400.0


In [ ]:
def QL_test(Q,A,C,I,S):
    i = C.shape[0]-1
    S_star = np.zeros(i)
    D_star = np.zeros(i)
    while True:
        S_star[i] = np.sqrt(2*A*Q/(I*C[i]))
        if S[i]<=S_star[i]<S[i+1]:
            check = []
            D_star[i] = val(C[i],S_star[i])
            check.append(D_star[i])
            for k in range(i,len(S)):
                check.append(val(C[k],S_star[k]))
        


# Ràng buộc về dung tích kho

In [3]:
A = np.array([50,75,100]) # Chi phí đặt hàng
C = np.array([20,100,50]) # Gía 1 đơn vị hàng loại i
Q = np.array([1000,500,2000]) # Nhu cầu
I = 0.2
F = 14000
f = np.array([]) # Dung tích kho để chứa 1 đơn vị hàng


def eval(lda):
    #l = lda*np.ones(n)
    S_star = np.sqrt((2*A*Q)/(I*C+2*lda*f))
    F_overline = np.dot(f,S_star)
    if F_overline==F:
        print("lambda đã cho là giá trị cần tìm")
    else:
        print("Thử giá trị lambda khác")
def eval1(S_star):
    F_overline = np.dot(f,S_star)
    if F_overline<=F:
        print("S* là nghiệm tối ưu")
    else:
        lda = (((2*A*Q)/(S_star**2))-I*C)/(2*f)
        if lda>=0:
            print("S* là nghiệm tối ưu")
        else:
            print("S* không phải nghiệm tối ưu")


# Ràng buộc về vốn

In [17]:
A = np.array([50,75,100]) # Chi phí đặt hàng
c = np.array([20,100,50]) # Vốn dành cho 1 đơn vị hàng loại i
Q = np.array([1000,500,2000]) # Nhu cầu
I = 0.2
C = 14000 # Vốn tối đa

S_star = np.sqrt((2*A*Q)/(I*c))
if np.dot(c,S_star)<=C:
    print("Nghiệm tối ưu là:\n ",S_star)
else:
    lda = ((np.dot(c,np.sqrt((2*A*Q)/c))/C)**2 - I)/2
    print("Lambda = ",lda)
    S_star = np.sqrt((2*A*Q)/(I*c+2*lda*c))
    print("Nghiệm tối ưu là:\n ",S_star)




Lambda =  0.08977034377785745
Nghiệm tối ưu là:
  [114.77725452  44.45303953 145.18301914]


# Dòng erglang

In [32]:
def sum_(alpha,n):
    tmp = 0
    for i in range(0,n+1):
        tmp += (alpha**i)/math.factorial(i)
    return tmp
def test(alpha,P_tc_max): # Hàm tính số kênh tối thiểu phải dùng
    n=0
    while True:
        P_tc = (alpha**n/math.factorial(n))*(1/sum_(alpha,n))    
        if P_tc<P_tc_max:
            print("Cần ít nhất số kênh là: ",n)
            break
        else:
            n += 1
            continue
    return n
def cal(n,u,lda):
    alpha = lda/u
    P0 = 1/sum_(alpha,n)
    print("Xác suất rỗi là: ",P0)
    P_tc = (alpha**n/math.factorial(n))*P0
    print("Xác suất từ chối là: ",P_tc)
    P_pv = 1-P_tc
    print("Xác suất phục vụ: ",P_pv)
    N_b = alpha*P_pv 
    print("Số kênh bận trung bình là: ",N_b)
    H_b = N_b/n
    print("Hệ số bận trung bình: ",H_b)
    H_r = 1-H_b
    print("Hệ số rỗi trung bình: ",H_r)
    Q = lda*P_pv
    print('Số yêu cầu được phục vụ trong 1 đv thời gian: ',Q)
    test(alpha,0.2)

n = 6 # Số kênh phục vụ của hệ thống
u = 2 # Cường độ phục vụ của hệ thống (năng suất)
lda = 4 # Cường độ dòng vào của hệ thống
cal(n,u,lda)
# test(alpha,0.2)

Xác suất rỗi là:  0.13595166163141995
Xác suất từ chối là:  0.012084592145015107
Xác suất phục vụ:  0.9879154078549849
Số kênh bận trung bình là:  1.9758308157099698
Hệ số bận trung bình:  0.3293051359516616
Hệ số rỗi trung bình:  0.6706948640483383
Số yêu cầu được phục vụ trong 1 đv thời gian:  3.9516616314199395
Cần ít nhất số kênh là:  4


In [40]:
u = 1/10 # Cường độ phục vụ của hệ thống (năng suất)
lda = 75000/(365*455) # Cường độ dòng vào của hệ thống
alpha = lda/u
n = test(alpha,0.05)
print("Diện tích cần thiết kế là: ",n*455/0.65)

Cần ít nhất số kênh là:  8
Diện tích cần thiết kế là:  5600.0


In [25]:
def profit(n,u,lda,cp,money):
    """
        n : số kênh phục vụ
        cp : chi phí duy trì mỗi kênh
        money : số tiền hệ thống nhận được cho mỗi nhu cầu
    """
    alpha = lda/u
    P0 = 1/sum_(alpha,n)
    P_tc = (alpha**n/math.factorial(n))*P0
    print("Xác suất từ chối là: ",P_tc)
    P_pv = 1-P_tc
    print("Xác suất phục vụ: ",P_pv)
    N_b = alpha*P_pv 
    print("Số kênh bận trung bình là: ",N_b)
    H_b = N_b/n
    print("Hệ số bận: ",H_b)
    H_r = 1-H_b
    print("Hệ số rỗi: ",H_r)
    Q = lda*P_pv
    print('Số yêu cầu được phục vụ trong 1 đv thời gian: ',Q)
    print("Tiền lãi của hệ thống với "+str(n)+" kênh trong 1h là: ",Q*money-n*cp)
# n = 3 # Số kênh phục vụ của hệ thống
u = 1 # Cường độ phục vụ của hệ thống (năng suất)
lda = 2 # Cường độ dòng vào của hệ thống
profit(3,u,lda,10000,25000)
profit(4,u,lda,10000,25000)

Xác suất từ chối là:  0.2105263157894737
Xác suất phục vụ:  0.7894736842105263
Số kênh bận trung bình là:  1.5789473684210527
Hệ số bận:  0.5263157894736842
Hệ số rỗi:  0.4736842105263158
Số yêu cầu được phục vụ trong 1 đv thời gian:  1.5789473684210527
Tiền lãi của hệ thống với 3 kênh trong 1h là:  9473.684210526313
Xác suất từ chối là:  0.09523809523809523
Xác suất phục vụ:  0.9047619047619048
Số kênh bận trung bình là:  1.8095238095238095
Hệ số bận:  0.4523809523809524
Hệ số rỗi:  0.5476190476190477
Số yêu cầu được phục vụ trong 1 đv thời gian:  1.8095238095238095
Tiền lãi của hệ thống với 4 kênh trong 1h là:  5238.095238095237


In [33]:
def profit2(T,n,u,lda,C_pv,C_kr,C_kb,C_tc):
    """
        n : số kênh phục vụ
        C_pv : giá trị lợi nhuận phục vụ một yêu cầu
        C_tc : Gía trị tổn thất nếu một yêu cầu bị từ chối
        C_kr : Tổn thất cho một kênh không làm việc trong một đơn vị thời gian
        C_kb : Chi phí cho một kênh làm việc trong một đơn vị thời gian
    """
    alpha = lda/u
    print(test(alpha,0.2))
    P0 = 1/sum_(alpha,n)
    P_tc = (alpha**n/math.factorial(n))*P0
    print("Xác suất từ chối là: ",P_tc)
    P_pv = 1-P_tc
    print("Xác suất phục vụ: ",P_pv)
    N_b = alpha*P_pv 
    N_r = n-N_b
    print("Số kênh bận trung bình là: ",N_b)
    # H_b = N_b/n
    # print("Hệ số bận: ",H_b)
    # H_r = 1-H_b
    # print("Hệ số rỗi: ",H_r)
    # Q = lda*P_pv
    # print('Số yêu cầu được phục vụ trong 1 đv thời gian: ',Q)
    print("Tiền lãi của hệ thống với "+str(n)+" kênh trong 1h là: ",(lda*P_pv*C_pv-lda*P_tc*C_tc-N_b*C_kb-N_r*C_kr))
u = 2
lda = 4
profit2(10,6,u,lda,15000,40000/10,100000/10,0)

Cần ít nhất số kênh là:  4
4
Xác suất từ chối là:  0.012084592145015107
Xác suất phục vụ:  0.9879154078549849
Số kênh bận trung bình là:  1.9758308157099698
Tiền lãi của hệ thống với 6 kênh trong 1h là:  23419.93957703927


# Hệ thống chờ thuần nhất (thời gian và độ dài hàng chờ vô hạn)

In [65]:
def sum_(alpha,n):
    tmp = 0
    for i in range(0,n+1):
        tmp += (alpha**i)/math.factorial(i)
    return tmp
def sum__(alpha,n):
    tmp = 0
    for i in range(0,n+1):
        tmp += ((n-i)*(alpha**i))/math.factorial(i)
    return tmp
def test(alpha,P_tc_max): # Hàm tính số kênh tối thiểu phải dùng cho P_chờ
    n=int(alpha)+1

    while True:
        # print(alpha**(n+1)/(math.factorial(n)*(n-alpha)))
        # print(sum_(alpha,n))
        P0 = 1/(sum_(alpha,n)+alpha**(n+1)/(math.factorial(n)*(n-alpha)))
        P_tc = (alpha**n/((math.factorial(n-1))*(n-alpha)))*P0
        
        if P_tc<P_tc_max:
            print("Cần ít nhất số kênh là: ",n)
            break
        else:
            n += 1
            continue
    return n
def test1(alpha,M_max): # Hàm tính số kênh tối thiểu phải dùng cho M_c
    n=int(alpha)+1

    while True:
        # print(alpha**(n+1)/(math.factorial(n)*(n-alpha)))
        # print(sum_(alpha,n))
        P0 = 1/(sum_(alpha,n)+alpha**(n+1)/(math.factorial(n)*(n-alpha)))
        Mc = (alpha**(n+1)/((math.factorial(n-1))*(n-alpha)**2))*P0
        
        if Mc<M_max:
            print("Cần ít nhất số kênh là: ",n)
            break
        else:
            n += 1
            continue
    return n
def profit3(lda,u,n,s,k):
    """
        n : số kênh phục vụ
        s : số yêu cầu đang chờ để phục vụ
        k : số kênh bận (đầu bài cho)
    """
    alpha = lda/u
    if alpha/n<1:
        P0 = 1/(sum_(alpha,n)+alpha**(n+1)/(math.factorial(n)*(n-alpha)))
        print("Xác suất tất cả các kênh đều rỗi : ",P0)
        Pk = (alpha**(k)*P0)/(math.factorial(k))
        print("Xác suất hệ thống có k kênh bệnh (k<n) : ",Pk)
        Pns = (alpha**n/(math.factorial(n)))*((alpha/n)**s)*P0
        print("Xác suất hệ thống có n kênh bận và s yêu cầu chờ : ",Pns)
        Pc = (alpha**n/((math.factorial(n-1))*(n-alpha)))*P0
        print("Xác suất chờ : ",Pc)
        Ppv = 1-Pc
        print("Xác suất phục vụ : ",Ppv)
        Mc_overline = (alpha**(n+1)/((math.factorial(n-1))*(n-alpha)**2))*P0
        print("Độ dài hàng chờ trung bình : ",Mc_overline) 
        tc_overline = Mc_overline/lda
        print("Thời gian chờ trung bình : ",tc_overline) 
        Nr_overline = P0*sum__(alpha,n)
        print("Số kênh rỗi trung bình : ",Nr_overline)
        Nb_overline = n-Nr_overline
        print("Số kênh bận trung bình : ",Nb_overline)
        test1(alpha,6)
lda = 8
u = 3
n = 3
s = 10
k=1
profit3(lda,u,n,s,k)


Xác suất tất cả các kênh đều rỗi :  0.028037383177570107
Xác suất hệ thống có k kênh bệnh (k<n) :  0.07476635514018695
Xác suất hệ thống có n kênh bận và s yêu cầu chờ :  0.027287716787921183
Xác suất chờ :  0.7975077881619936
Xác suất phục vụ :  0.20249221183800636
Độ dài hàng chờ trung bình :  6.3800623052959455
Thời gian chờ trung bình :  0.7975077881619932
Số kênh rỗi trung bình :  0.3333333333333335
Số kênh bận trung bình :  2.6666666666666665
Cần ít nhất số kênh là:  4


# Hệ thống chờ thuần nhất (thời gian và độ dài hàng chờ hạn chế)

In [66]:
def sum_(alpha,n):
    tmp = 0
    for i in range(0,n+1):
        tmp += (alpha**i)/math.factorial(i)
    return tmp
def sum__(alpha,n,m):
    tmp = 0
    for i in range(1,m+1):
        tmp += (alpha/n)**i
    return tmp
def sum___(alpha,n,m):
    tmp = 0
    for i in range(0,m):
        tmp += (alpha/n)**i
    return tmp
def sum____(alpha,n,k):
    tmp = 0
    for i in range(0,n+1):
        tmp += ((alpha)**i/(math.factorial(i)))*k
    return tmp
def sum_____(alpha,n,m):
    tmp = 0
    for i in range(1,m+1):
        tmp += (alpha/n)**i
    return tmp
def sum______(alpha,n,m):
    tmp = 0
    for i in range(1,m+1):
        tmp += i*(alpha/n)**i
    return tmp
def profit4(lda,u,n,s,k,m):
    """
        n : số kênh phục vụ
        s : số yêu cầu đang chờ để phục vụ
        k : số kênh bận (đầu bài cho)
        m : số chỗ xếp hàng chờ
    """
    alpha = lda/u   
    P0 = 1/(sum_(alpha,n)+(alpha**(n)*sum__(alpha,n,m))/(math.factorial(n)))  
    print("Xác suất tất cả các kênh đều rỗi : ",P0)
    Pk = (alpha**(k)*P0)/(math.factorial(k))
    print("Xác suất hệ thống có k kênh bệnh (k<n) : ",Pk)
    Pns = (alpha**n/(math.factorial(n)))*((alpha/n)**s)*P0
    print("Xác suất hệ thống có n kênh bận và s yêu cầu chờ : ",Pns)
    Ptc = (alpha**n/(math.factorial(n))*((alpha/n)**m))*P0
    print("Xác từ chối : ",Ptc)
    Ppv = 1-Ptc
    print("Xác suất phục vụ : ",Ppv)
    Pc = ((alpha)**n/(math.factorial(n)))*P0*sum___(alpha,n,m)
    print("Xác suất 1 yêu cầu đến hệ thống phải chờ là : ",Pc)
    Popv = 1-Ptc-Pc
    print("Xác suất 1 yêu cầu đến hệ thống được phục vụ ngay là : ",Popv)
    Mc_overline = (alpha**(n)/(math.factorial(n)))*(sum______(alpha,n,m))*P0
    print("số yêu cầu chờ trung bình : ",Mc_overline) 
    tc_overline = Mc_overline/lda
    print("Thời gian chờ trung bình : ",tc_overline) 
    Nb_overline = P0*(sum____(alpha,n,k)+((alpha)**n/(math.factorial(n-1)))*sum_____(alpha,n,m))
    print("Số kênh bận trung bình : ",Nb_overline)
    Nr_overline = n-Nb_overline
    print("Số kênh rỗi trung bình : ",Nr_overline)
    Q = lda*Ppv
    print("Số yêu cầu được phục vụ trong 1 đv thời gian : ",Q)
lda = 16
u = 5
n = 4
s = 1
k = 1
m = 4
profit4(lda,u,n,s,k,m)


Xác suất tất cả các kênh đều rỗi :  0.033934669430494356
Xác suất hệ thống có k kênh bệnh (k<n) :  0.10859094217758195
Xác suất hệ thống có n kênh bận và s yêu cầu chờ :  0.1186102664425002
Xác từ chối :  0.06072845641856011
Xác suất phục vụ :  0.9392715435814399
Xác suất 1 yêu cầu đến hệ thống phải chờ là :  0.43767188317282574
Xác suất 1 yêu cầu đến hệ thống được phục vụ ngay là :  0.5015996604086141
số yêu cầu chờ trung bình :  0.7790322299943413
Thời gian chờ trung bình :  0.04868951437464633
Số kênh bận trung bình :  2.050412519614782
Số kênh rỗi trung bình :  1.949587480385218
Số yêu cầu được phục vụ trong 1 đv thời gian :  15.028344697303039


In [61]:
68/31

2.193548387096774

In [20]:
import logging

# PERT implemtnion in python

#Tal Cohen : 308275429

#Shlomi Shasho: 308140557

class LogMixin (object):
    @property
    def logger(self):
        name = '.'.join([__name__, self.__class__.__name__])
        return logging.getLogger (name)

logging.basicConfig (level=logging.INFO, filename='PERT_log.log', filemode='w',
                     format='%(asctime)s : %(name)-10s - %(levelname)-5s - %(funcName)20s() : %(message)s')

class Activity (LogMixin):
    def __init__(self, id_act, name, duration=0, description=None):
        self.id = id_act
        self.name = name
        self.duration = duration
        self.description = description

        # Earliest start time.
        self._es = 0
        # Latest start time.
        self._ls = 0
        # The amount of time that the activity can be delayed without
        # increasing the overall project's duration.
        self._slacktime = 0
        self.to_nodes = []
        self.incoming_nodes = []
        self.logger.info ("New activity created :" + self.name + " duration: " + str (self.duration) + " description: ")

    def __str__(self):
        str_activity = 'Activity %d : %s , %d days' % (self.id, self.name, self.duration)
        self.logger.info (str_activity)
        return str_activity

    def __repr__(self):
        return "(Activity %d : %s , %d days)" % (self.id, self.name, self.duration)

    @property
    def es(self):
        return self._es

    @property
    def ls(self):
        return self._ls

    @property
    def slacktime(self):
        return self._slacktime

    @es.setter
    def es(self, es):
        if es >= 0:
            self._es = es
        else:
            self._es = 0
        self.logger.info ("activity: " + self.name + " es: " + str (self.es))
        pass

    @ls.setter
    def ls(self, ls):
        if ls >= 0:
            self._ls = ls
        else:
            self._es = 0
        self.logger.info ("activity: " + self.name + " ls: " + str (self.ls))
        pass

    @slacktime.setter
    def slacktime(self, slacktime):
        if slacktime >= 0:
            self._slacktime = slacktime
        else:
            self._slacktime = 0
        self.logger.info ("activity: " + self.name + " slacktime: " + str (self._slacktime))
        pass


class Project (LogMixin):
    def __init__(self, dic_project=None):
        # the dicationry is dicationry of Activity Object both for key and value
        if dic_project is None:
            dic_project = {}
        else:
            for k, v in dic_project.items():
                if not isinstance(Activity, k) or not isinstance(Activity,v):
                    self.logger.info("dicatonry must be with activity object, both for key and value " )
                    return
        self.logger.info("new Project was Created")
        self.dic_project = dic_project
        self._activityCounter = 0
        self.name_to_activity = {}
        self._duration = 0

    def add_activiy(self, name, duration):
        """ If the activity  "activity" is not in
            self.dic_project, a key "activty" with an empty
            list as a value is added to the dictionary.
            Otherwise nothing has to be done.
        """
        act = Activity (self._activityCounter, name, duration)
        self._activityCounter += 1
        if act not in self.dic_project:
            self.dic_project[act] = []
            self.name_to_activity[name] = act
        self.logger.info ("new activity was added " + str (act))

    def read_log_file(self):
        f = open('PERT_log.log')
        for i in f.readlines():
            print(i + "\n")

    def activity_in_graph(self, activity_name):
        """check if activity in dicatnory"""
        self.logger.info ("check if activity on graph for " + activity_name)
        if activity_name not in self.name_to_activity:
            self.logger.info ("activity " + activity_name + " is not on graph")
            return False
        self.logger.info ("activity " + activity_name + " is on graph")
        return True

    def add_edge(self, from_activityname, to_activityname=None):
        """add edge from from_activityname to : to_activityname
        between two activities can be multiple edges!"""

        self.logger.info ("adding edge between" + str ((from_activityname, to_activityname)))

        if not self.activity_in_graph (from_activityname) or not self.activity_in_graph (to_activityname):
            self.logger.info ("cant add edge- activtity isnt exist")
            return

        fromactivity = self.name_to_activity.get (from_activityname)
        to_activity = self.name_to_activity.get (to_activityname)

        if to_activity in fromactivity.to_nodes:
            self.logger.info ("allready has this edge")
            return

        fromactivity.to_nodes.append (to_activity)
        to_activity.incoming_nodes.append (fromactivity)
        self.update_list (fromactivity, to_activity)
        self.logger.info ("edge was added succefully")
        pass

    def update_list(self, *args):
        """update the list on the dicationry project to  speicif activity"""
        for activ in args:
            self.dic_project[activ] = list (set (activ.incoming_nodes + activ.to_nodes))
        pass

    def remove_activity(self, activitytoremove_name):
        """remove activity from graph """
        self.logger.info("remove activity" + activitytoremove_name)
        if not self.activity_in_graph (activitytoremove_name):
            self.logger.info("cant remove- acitivty doesnt exist in project")
            return

        activity_toremove = self.name_to_activity.get (activitytoremove_name)
        if activitytoremove_name == "end" or activitytoremove_name == "start":
            self.logger.info("cant remove the end or the start activity of the project")
            return

        for act in activity_toremove.to_nodes:
            if len (act.incoming_nodes) == 1:
                self.add_edge (activity_toremove.incoming_nodes[0].name, act.name)

        for act in self.dic_project[activity_toremove]:
            if activity_toremove in act.incoming_nodes:
                act.incoming_nodes.remove (activity_toremove)
            elif activity_toremove in act.to_nodes:
                act.to_nodes.remove (activity_toremove)
            self.update_list (act)

        del self.dic_project[activity_toremove]
        del self.name_to_activity[activity_toremove.name]
        self.logger.info ("acitivty: " + activitytoremove_name + "was removed succefully")

    def find_all_circles(self):
        """find circles from all the activites"""
        self.logger.info ("find all circles in graph")
        _circles_dic = {}
        for activ in self.dic_project.keys ():
            _circles_dic[activ.name] = self.find_all_paths (activ.name, activ.name, True)
        self.logger.info ("circles in graph :" + str (_circles_dic))
        return _circles_dic

    def find_all_paths(self, start_vertex, end_vertex, cycle_check=False, path=None):
        """ find all paths from start_vertex to end_vertex
            in graph
            if boolean cycleCheck is TRUE so try to look for circle and not a straight path
            Recursive function"""
        if path is None:
            path = []
        if not self.activity_in_graph (start_vertex) or not self.activity_in_graph (end_vertex):
            return None

        self.logger.info ("find path from " + start_vertex + " to: " + end_vertex)
        self.logger.info ("check for cycle?" + str (cycle_check))
        start_vertex_act = self.name_to_activity.get (start_vertex)
        end_vertex_act = self.name_to_activity.get (end_vertex)
        graph = self.dic_project
        path = path + [start_vertex_act.name]
        if start_vertex_act == end_vertex_act and not cycle_check:
            return [path]
        if start_vertex_act not in graph:
            return None

        paths = []
        for act in start_vertex_act.to_nodes:
            if act.name not in path or act == end_vertex_act:
                extended_paths = self.find_all_paths (act.name, end_vertex, False, path)
                if extended_paths:
                    paths += extended_paths
                # for p in extended_paths:
                #     paths.append(p)
        self.logger.info ("all paths are : " + str (paths))

        return paths

    def find_isolated(self):
        """find isolated activites: activites with no descending or asscending activites """
        self.logger.info ("find_isolated()")
        isolated__activities = []
        for activity in self.dic_project:
            if len (activity.incoming_nodes) == 0 or len (activity.to_nodes) == 0:
                isolated__activities.append (activity.name)
        self.logger.info ("isloated activites" + str (isolated__activities))
        return isolated__activities


    def find_critical_path(self, start_vertex, end_vertex):
        #     return "critical path is from the first activity to the end"
        if not self.activity_in_graph (start_vertex) or not self.activity_in_graph (end_vertex):
            return None

        self.logger.info (f"find_critical_path({start_vertex},{end_vertex})")
        all_paths = self.find_all_paths (start_vertex, end_vertex)
        durations_list = list (map (self.calculate_duration, all_paths))
        if durations_list:
            max_duration = max (durations_list)
            max_loc = durations_list.index (max_duration)
            crit_path_list = [(node, self.name_to_activity.get (node).duration) for node in all_paths[max_loc]]
        else:
            crit_path_list = None
        self.logger.info ("critical path is " + str (crit_path_list))
        return crit_path_list

    @property
    def duration(self):
        """duration of all project by the critical path """
        critical = self.find_critical_path ("start", "end")
        crit = [path[0] for path in critical]
        self._duration = self.calculate_duration (crit)
        self.logger.info ("self.duration" + str (self._duration))
        return self._duration

    def calculate_duration(self, path):
        """calculate duration to a given path
            path is a list of activity names"""
        self.logger.info ("calculate_duration of a path " + str (path))
        sum_duration = 0
        for vertex_name in path:
            act = self.name_to_activity.get (vertex_name)
            sum_duration += act.duration
        self.logger.info ("calculate_duration() of a path " + str (path) + ": " + str (sum_duration))
        return sum_duration

    def find_es(self, start_activity):
        """update the earlist_time to start each activity"""
        self.logger.info (f"find_es({start_activity})")
        isolated_list = self.find_isolated ()
        for act in self.dic_project:
            if act.name not in isolated_list or act.name == "end":
                critical_temp = self.find_critical_path (start_activity, act.name)
                crit = [path[0] for path in critical_temp]
                act.es = self.calculate_duration (crit) - act.duration
            else:
                act.es = 0
            self.logger.info ("activity:" + act.name + " es : " + str (act.es))
        pass

    def find_ls(self, start_activity):
        """find the latest time to start each activity"""
        self.logger.info (f"find_es({start_activity})")
        isolated_list = self.find_isolated ()
        for act in self.dic_project:
            if act.name not in isolated_list or act.name == "start":
                critical_temp = self.find_critical_path (start_activity, act.name)
                crit = [path[0] for path in critical_temp]
                act.ls = self._duration - (self.calculate_duration (crit))
            else:
                act.ls = self._duration - act.duration
            self.logger.info ("activity:" + act.name + " ls : " + str (act.ls))
        pass

    def change_direction(self):
        """change the direction of the graph
        use only in function calculate_slack_time() """
        self.logger.info ("change_direction()")
        for act in self.dic_project:
            temp = act.incoming_nodes
            act.incoming_nodes = act.to_nodes
            act.to_nodes = temp


    def exist_circles(self):
        """check if there is circles in the project"""
        check = False
        if not self.find_all_circles():
            check = True
        self.logger.info("exist circles " + str(check))
        return check

    def calculate_slack_time(self):
        """calculate the slack time for all activities
        note : cant calculate slack time if there are circles in the graph"""
        self.logger.info ("calculate_slack_time()")
        if self.exist_circles():
            self.logger.info ("there are cycles in the graph, cant calculate slack time .. return ")
            return

        self.find_es ("start")
        duration = self.duration
        self.change_direction ()
        self.find_ls ("end")
        self.change_direction ()

        for activ_to_calculate in self.dic_project:
            activ_to_calculate.slacktime = activ_to_calculate.ls - activ_to_calculate.es
        slacktime_list = ([(node, node.slacktime) for node in self.dic_project if node.slacktime is not 0])
        slacktime_list.sort (key=lambda x: x[1])
        self.logger.info ("slack time calculated: " + str (slacktime_list))
        return slacktime_list

    def __str__(self):
        project_string ="-names of activites in project: \n"+str(self.name_to_activity.keys())
        project_string += "\n -all edges  in project :\n"
        for k in self.dic_project.keys():
            for v in k.to_nodes:
                project_string+="("+str(k)+")---->("+str(v)+")\n"

        # project_string = "-all activites in project :\n" + str (self.dic_project)
        project_string += "\n-paths from start to end : \n" + str (self.find_all_paths ("start", "end"))
        circles = self.find_all_circles ()
        if not circles:
            project_string += "\n Circles in graph: \n" + str (circles)
        else:
            project_string += "\n-There are no Circles in Graph"
            project_string += "\n-Total duration of Project: " + str (self.duration)
            project_string += "\n-critical path in the project: \n" + str(self.find_critical_path("start", "end"))
            slacklist = self.calculate_slack_time ()
            project_string += "\n-slack time by descending order ( without critical path nodes) :\n" + str (slacklist)
            self.logger.info(project_string)

        return project_string


if __name__ == "__main__":
# assuming that the project start with start activity , end with end activity - Mica's order
    p = Project()
    # p.add_activiy ("start", 0)
    # p.add_activiy ("2", 2)
    # p.add_activiy ("3", 4)
    # p.add_activiy ("4", 10)
    # p.add_activiy ("5", 4)
    # p.add_activiy ("6", 6)
    # p.add_activiy ("7", 12)
    # p.add_activiy ("8", 7)
    # p.add_activiy ("9", 8)
    # p.add_activiy ("10", 9)
    # p.add_activiy ("11", 4)
    # p.add_activiy ("12", 5)
    # p.add_activiy ("end", 8)
    p.add_activiy ("start", 0)
    p.add_activiy ("2", 2)
    p.add_activiy ("3", 3)
    p.add_activiy ("4", 6)
    p.add_activiy ("5", 2)
    p.add_activiy ("6", 10)
    p.add_activiy ("end", 13)

    # The Project Dicationary: (activity,name,duration)
    # {(Activity 0: start, 2 days): [], (Activity 1: A, 1 days): [], (Activity 2: B, 3 days): [],
    #  (Activity 3: C, 12 days): [], (Activity 4: D, 2 days): [], (Activity 5: E, 1 days): [],
    #  (Activity 6: F, 6 days): [], (Activity 7: end, 2 days): []}

    # p.add_edge("start", "2")
    # p.add_edge ("2", "3")
    # p.add_edge ("3", "4")
    # p.add_edge ("4", "5")
    # p.add_edge ("4", "6")
    # p.add_edge ("4", "7")
    # p.add_edge ("5", "7")
    # p.add_edge ("6", "8")
    # p.add_edge ("7", "9")
    # p.add_edge ("8", "10")
    # p.add_edge ("9", "11")
    # p.add_edge ("9", "12")
    # p.add_edge("10", "end")
    # p.add_edge("12", "end")
    p.add_edge("start", "2")
    p.add_edge ("start", "3")
    p.add_edge ("2", "4")
    p.add_edge ("3", "4")
    p.add_edge ("3", "5")
    p.add_edge ("4", "5")
    p.add_edge ("5", "6")
    p.add_edge ("4", "6")
    p.add_edge ("4", "end")
    p.add_edge ("5", "end")
    p.add_edge ("6", "end")
    print ()
    print (p)

    # read from lof file and print
    # p.read_log_file()

    # case of add activity and remove
    # print ()
    # p.add_activiy("S",1)
    # p.add_edge("S","F")
    # print(p)
    # print ()
    # p.remove_activity("S")
    # print(p)


-names of activites in project: 
dict_keys(['start', '2', '3', '4', '5', '6', 'end'])
 -all edges  in project :
(Activity 0 : start , 0 days)---->(Activity 1 : 2 , 2 days)
(Activity 0 : start , 0 days)---->(Activity 2 : 3 , 3 days)
(Activity 1 : 2 , 2 days)---->(Activity 3 : 4 , 6 days)
(Activity 2 : 3 , 3 days)---->(Activity 3 : 4 , 6 days)
(Activity 2 : 3 , 3 days)---->(Activity 4 : 5 , 2 days)
(Activity 3 : 4 , 6 days)---->(Activity 4 : 5 , 2 days)
(Activity 3 : 4 , 6 days)---->(Activity 5 : 6 , 10 days)
(Activity 3 : 4 , 6 days)---->(Activity 6 : end , 13 days)
(Activity 4 : 5 , 2 days)---->(Activity 5 : 6 , 10 days)
(Activity 4 : 5 , 2 days)---->(Activity 6 : end , 13 days)
(Activity 5 : 6 , 10 days)---->(Activity 6 : end , 13 days)

-paths from start to end : 
[['start', '2', '4', '5', '6', 'end'], ['start', '2', '4', '5', 'end'], ['start', '2', '4', '6', 'end'], ['start', '2', '4', 'end'], ['start', '3', '4', '5', '6', 'end'], ['start', '3', '4', '5', 'end'], ['start', '3', '4'

# Đường găng

In [8]:
import logging
import unittest
import itertools

def log_with_msg(msg):
    def log(func):
        def wrapper(self, *args, **kwargs):
            logging.getLogger(__name__ + ": ").info(msg)
            return func(self, *args, **kwargs)
        return wrapper
    return log

class Activity:
    """
        The Activity class
        -------------------
        represents the edges between each node
        Each activity has a unique name and its duration in the project
        Activities will be equal if their name and their duration is the same
    """

    @log_with_msg("Initializing Activity")
    def __init__(self, name, duration):
        self._name = name
        self._duration = duration

    @log_with_msg("Returning Activity repr")
    def __repr__(self) -> str:
        return f"<{self.name}, {self.duration} weeks>"

    @log_with_msg("Returning Activity str")
    def __str__(self) -> str:
        return f"<{self.name}, {self.duration} weeks>"

    @property
    def name(self) -> str:
        return self._name

    @name.setter
    def name(self, name):
        self._name = name

    @property
    def duration(self) -> float:
        return self._duration

    @duration.setter
    def duration(self, duration):
        self._duration = duration

    @log_with_msg("Comparing Activities")
    def __eq__(self, other) -> bool:
        return self.name == other.name and self.duration == other.duration

    def __ne__(self, other) -> bool:
        return not self == other


class Node:
    """
        The Node class
        --------------
        represents the actual node in the graph.
        knows the early and late finish times and also knows the slack time
        Each node is unique and is recognized by its number.
        A node is equal to another node if their number is equal (regardless of the other properties)
        It is set that way to keep the nodes unique
        Each node has an optional parallel node. If a node has a parallel node,
        both activities leading to those nodes must be completed together
    """

    @log_with_msg("Initializing Node")
    def __init__(self, number: int, *parallel_nodes: "List of Nodes"):
        self._number = number
        self._early_finish = 0
        self._late_finish = 0
        self._slack = 0
        self._parallel_nodes = parallel_nodes

    @log_with_msg("Returning Node repr")
    def __repr__(self) -> repr:
        return f"(Node {self.number})"

    @log_with_msg("Returning Node str")
    def __str__(self) -> str:
        string = f"(Node {self.number})"
        if not (self.late_finish == self.early_finish == 0):
            string += f"{[self.early_finish,self.late_finish]}"
        if self.has_parallel_nodes():
            string += " <---> {"
            for node in list(self.parallel_nodes)[:-1]:
                string += f"{node}, "
            string += f"{self.parallel_nodes[-1]}" + "}"
        return string

    @property
    def early_finish(self) -> float:
        return self._early_finish

    @early_finish.setter
    def early_finish(self, early_finish):
        self._early_finish = early_finish

    @property
    def late_finish(self) -> float:
        return self._late_finish

    @late_finish.setter
    def late_finish(self, late_finish):
        self._late_finish = late_finish

    @property
    def slack(self) -> float:
        return self._slack

    @slack.setter
    def slack(self, slack: float):
        self._slack = slack

    @property
    def number(self) -> int:
        return self._number

    @number.setter
    def number(self, number: int):
        self._number = number

    @property
    def parallel_nodes(self) -> tuple:
        return self._parallel_nodes

    @parallel_nodes.setter
    def parallel_nodes(self, *parallel_nodes: tuple):
        self._parallel_nodes = parallel_nodes

    @log_with_msg("Checking if Node has parallel nodes")
    def has_parallel_nodes(self) -> bool:
        return list(self.parallel_nodes) != []

    @log_with_msg("Comparing Nodes")
    def __eq__(self, other) -> bool:
        return self.number == other.number

    def __ne__(self, other) -> bool:
        return not self == other

    @log_with_msg("Hashing Node")
    def __hash__(self) -> float:
        return hash(self.number)

    # For sorting purposes
    @log_with_msg("Checking what node is bigger")
    def __lt__(self, other) -> bool:
        return self.number < other.number

class Transition:
    """
        Transition class
        ----------------
        represents the transitions from one node to another.
        keeps track of the activity, the start node and the target node
    """

    @log_with_msg("Initializing Transition")
    def __init__(self, from_node: Node, activity: Activity, to_node: Node):
        self._from_node = from_node
        self._activity = activity
        self._to_node = to_node

    @log_with_msg("Returning Transition repr")
    def __repr__(self) -> repr:
        return f"({repr(self._from_node)}, {self._activity}, {repr(self._to_node)})"

    @log_with_msg("Returning Transition str")
    def __str__(self) -> str:
        return f" {self.from_node} -> {self._activity} -> {self._to_node}"

    @property
    def from_node(self) -> Node:
        return self._from_node

    @from_node.setter
    def from_node(self, from_node: Node):
        self._from_node = from_node

    @property
    def to_node(self) -> Node:
        return self._to_node

    @to_node.setter
    def to_node(self, to_node: Node):
        self._to_node = to_node

    @property
    def activity(self) -> Activity:
        return self._activity

    @activity.setter
    def activity(self, activity: Activity):
        self._activity = activity

    @log_with_msg("Comparing Transitions")
    def __eq__(self, other) -> bool:
        return self.activity == other.activity

    def __ne__(self, other) -> bool:
        return not self == other


class Project:
    """
    The Pert class
    --------------
    The class which represents the pert, using a graph.
    The graph is a dictionary of {Node : list(Transition)} - each node with the corresponding transitions from it.
    If no graph was passed to the constructor, an empty graph is initialized
    """

    @log_with_msg("Initializing new PERT")
    def __init__(self, graph: dict = None):
        self._graph = graph if graph is not None else {}
        self._all_nodes = []
        self._all_paths = []
        self._all_transition = []
        self._all_activities = []
        self._slack_list = []
        self._isolated_list = []
        self._critical_paths = []
        self._start = None
        self._end = None
        self.update()

    @log_with_msg("Printing PERT")
    def __str__(self) -> str:
        string = '!!WARNING: Invalid Graph!!' if not self.is_valid() else ''
        for path in self.all_paths:
            string += f"\nCRITICAL PATH: " if path in self.critical_paths else f"\n" + "\t" * 3 + " " * 3
            for count, n in enumerate(path[:-1]):
                if n == self.start:
                    string += f"{([trans for trans in self.graph[path[count]] if trans.to_node == path[count + 1]])[0]}"
                elif self.end is not None and n == self.end:
                    string += f" -> {self.graph[path[count-1]][0].activity} -> {n}"
                else:
                    for trans in self.graph[n]:
                        if trans.to_node == path[count + 1]:
                            string += f"-> {trans.activity} -> {trans.to_node}"
                            break
            string += '\n'
        return string

    @property
    def graph(self) -> dict:
        return self._graph

    @graph.setter
    def graph(self, graph: dict):
        self._graph = graph
        self.update() if graph else self.__nullify_graph__()

    @property
    def all_nodes(self) -> list:
        return self._all_nodes

    @all_nodes.setter
    def all_nodes(self, all_nodes: list):
        self._all_nodes = all_nodes

    @property
    def all_paths(self) -> list:
        return self._all_paths

    @all_paths.setter
    def all_paths(self, all_paths: list):
        self._all_paths = all_paths

    @property
    def all_transition(self) -> list:
        return self._all_transition

    @all_transition.setter
    def all_transition(self, all_transition: list):
        self._all_transition = all_transition

    @property
    def all_activities(self) -> list:
        return self._all_activities

    @all_activities.setter
    def all_activities(self, all_activities: list):
        self._all_activities = all_activities

    @property
    def slack_list(self) -> list:
        return self._slack_list

    @slack_list.setter
    def slack_list(self, slack_list: list):
        self._slack_list = slack_list

    @property
    def isolated_list(self) -> list:
        return self._isolated_list

    @isolated_list.setter
    def isolated_list(self, isolated_list: list):
        self._isolated_list = isolated_list

    @property
    def critical_paths(self) -> list:
        return self._critical_paths

    @critical_paths.setter
    def critical_paths(self, critical_paths: list):
        self._critical_paths = critical_paths

    @property
    def start(self) -> Node:
        return self._start

    @start.setter
    def start(self, start: Node):
        self._start = start

    @property
    def end(self) -> Node:
        return self._end

    @end.setter
    def end(self, end: Node):
        self._end = end

    # nullifies the graph's properties
    @log_with_msg("Nullifying PERT")
    def __nullify_graph__(self):
        self.all_nodes = []
        self.all_transition = []
        self.isolated_list = []
        self.all_paths = []
        self.all_activities = []
        self.slack_list = []
        self.critical_paths = []
        self.start = None
        self.end = None

    # calculates the early finished, the late finishes, the slack times and the duration of the project
    @log_with_msg("Updating PERT")
    def update(self):
        if self.graph is not None:
            self.all_nodes = self.__get_all_nodes__()
            self.all_transition = self.__get_transition_list__()
            self.isolated_list = self.__get_isolated_nodes__()
            self.start = self.__get_start_node__()
            self.end = self.__get_end_node__()
            self.all_paths = self.__find_all_paths__(self.start)
            self.all_activities = self.__get_activities_list__()
            self.__calc_early_finishes__()
            self.__calc_late_finishes__()
            self.__calc_slack_times__()
            self.critical_paths = self.__get_critical_paths__()
            self.slack_list = self.__get_all_slacks__()

    # Return the length of the project
    @log_with_msg("Returning length of PERT")
    def __len__(self) -> float:
        return self.end.late_finish if self.graph is not None else 0

    # Returns a node from the graph which his number is node_number
    # @:param node_number - the number of the node which we want to retrieve
    @log_with_msg("Retrieving Node")
    def get_node_number(self, node_number: int) -> list or None:
        for node in self.all_nodes:
            if node.number == node_number:
                return node
        return None

    #  Adds a new activity to the project.
    #  @:param
    #  from_node - the node number from which the activity is going
    #  activity - the activity itself
    #  to_node - the node number to which the activity is going
    @log_with_msg("Adding Activity")
    def add_activity(self, from_node: int, activity: Activity, to_node: int):
        f_node = self.get_node_number(from_node)
        t_node = self.get_node_number(to_node)
        transition = Transition(f_node if f_node else Node(from_node), activity, t_node if t_node else Node(to_node))
        if transition not in self._all_transition:
            self.graph[transition.from_node] = self.graph[transition.from_node] + [
                transition] if transition.from_node in self.all_nodes else [transition]
            if transition.to_node not in self.all_nodes:
                self.graph[transition.to_node] = []
            self.update()

    # adds an arbitrary amount of transitions to the graph
    # @:param *args - list of transitions to be added to the graph
    def add_activities(self, *args: "List of Transitions"):
        for transition in args:
            self.add_activity(transition.from_node.number, transition.activity, transition.to_node.number)

    # Removes a transition from the graph which his activity is the argument passed, thus removing the activity too
    # @:param activity - the activity whom transition is deleted
    @log_with_msg("Deleting Activity")
    def del_activity(self, activity: Activity):
        for transitions in self.graph.values():
            for transition in transitions:
                if activity == transition.activity:
                    transitions.remove(transition)
        self.update()

    # Returns an activity list
    @log_with_msg("Getting Activity list")
    def __get_activities_list__(self) -> list:
        return [transition.activity for transition in self.all_transition]

    # Return a list of all nodes, including isolated nodes
    @log_with_msg("Getting all nodes")
    def __get_all_nodes__(self) -> list:
        return list(self.graph.keys()) if self.graph is not None else []

    # Returns the transition list
    @log_with_msg("Getting Transition list")
    def __get_transition_list__(self) -> list:
        return list(itertools.chain(*self.graph.values())) if self.graph is not None else []

    # Returns a list of isolated nodes =
    # nodes which none of the activities are going to, and none of the activities are going from
    @log_with_msg("Getting isolated nodes")
    def __get_isolated_nodes__(self) -> list:
        return [node for node in self.all_nodes if
                not self.graph[node] and node not in [tr.to_node for tr in self.all_transition]]

    # Returns the critical paths in the project
    # By definition - a critical path is a path which every node in it has 0 slack time
    @log_with_msg("Getting critical paths")
    def __get_critical_paths__(self) -> list:
        return [path for path in self.all_paths if not [node.slack for node in path if node.slack is not 0]]

    # Returns true if and only if this graph is valid, aka - has no cycles in it
    # NOTE : a cyclic path in the graph is for example :
    #       Node1->Node2->Node3->Node4->Node2
    @log_with_msg("Checking if valid")
    def is_valid(self) -> bool:
        return True not in [len(set(path)) < len(path) for path in self.all_paths]

    # Returns a sorted list of slack
    @log_with_msg("Getting all slack times")
    def __get_all_slacks__(self) -> list:
        return sorted([node.slack for node in self.all_nodes if node.slack is not 0], reverse=True)

    # Returns the starting node, not including isolated nodes
    @log_with_msg("Getting start nodes")
    def __get_start_node__(self) -> Node:
        for node in self.all_nodes:
            if node not in [tr.to_node for tr in self.all_transition] and node not in self.isolated_list:
                return node

    # Returns the ending node, not including isolated nodes
    # NOTICE: if the graph is cyclic, there might not be an end node, in this case, the returned value will be None
    @log_with_msg("Getting end node")
    def __get_end_node__(self) -> Node or None:
        for node in self.all_nodes:
            if not self.graph[node] and not node.has_parallel_nodes() and node not in self.isolated_list:
                return node
        return None

    # Calculates the early finishes possible
    @log_with_msg("Calculating early finishes")
    def __calc_early_finishes__(self):
        for node in list(itertools.chain(*self.all_paths)):
            for transition in self._graph[node]:
                transition.to_node.early_finish = transition.activity.duration + transition.from_node.early_finish \
                    if transition.to_node.early_finish is 0 else max(transition.to_node.early_finish,
                                                                     transition.from_node.early_finish +
                                                                     transition.activity.duration)
                for par_node in transition.to_node.parallel_nodes:
                    self.get_node_number(par_node.number).early_finish = max(transition.to_node.early_finish,
                                                                             par_node.early_finish)

    # Calculates the latest finishes possible
    @log_with_msg("Calculating late finishes")
    def __calc_late_finishes__(self):
        if self.end is not None:
            self.end.late_finish = self.end.early_finish
        for node in reversed(list(itertools.chain(*self.all_paths))):
            for transition in reversed(self.graph[node]):
                if transition.to_node.has_parallel_nodes():
                    late = min(
                        [self.get_node_number(par.number).late_finish for par in transition.to_node.parallel_nodes])
                    # if we haven't calculated late finish yet or if the late is smaller than the current late finish
                    if transition.to_node.late_finish is 0 or transition.to_node.late_finish > late:
                        transition.to_node.late_finish = late

                # if to_node.late_finish still 0, we can't compute its from_node.late_finish yet...
                if transition.to_node.late_finish is not 0:
                    transition.from_node.late_finish = transition.to_node.late_finish - transition.activity.duration \
                        if transition.from_node.late_finish is 0 and transition.from_node != self.start \
                        else min(transition.from_node.late_finish,
                                 transition.to_node.late_finish - transition.activity.duration)

    # Calculates the slack times for each node
    @log_with_msg("Calculating slack times")
    def __calc_slack_times__(self):
        for node in self.all_nodes:
            node.slack = node.late_finish - node.early_finish 

    # Finds all the paths in this project
    # The search will not include paths with isolated nodes.
    @log_with_msg("Finding all paths")
    def __find_all_paths__(self, start_node: Node, path: list = None) -> list:
        graph = self.graph
        path = path if path is not None else []
        if start_node in path or not graph[start_node]:
            return [path + [start_node]]
        path = path + [start_node]
        if start_node not in graph:
            return []
        paths = []
        for transition in graph[start_node]:
            paths += [path for path in self.__find_all_paths__(transition.to_node, path)]
        return paths

    # Implementation of the contains method.
    # Returns true if and only if the item is in this graph
    # An item can be of class Node, Activity or Transition
    @log_with_msg("Checking if item is in PERT")
    def __contains__(self, item) -> bool:
        if not (isinstance(item, Node) or isinstance(item, Activity) or isinstance(item, Transition)):
            raise PermissionError("this item doesnt belong to the pert!")
        return self.get_node_number(item.number) is not None if isinstance(item, Node) else \
            item in self.all_activities if isinstance(item, Activity) else item in self.all_transition

n = 6 # số nút
class TestPert2(unittest.TestCase):
    # node_list_2 = [Node(0),
    #                Node(1, Node(2)),
    #                Node(2),
    #                Node(3),
    #                Node(4, Node(3), Node(6)),
    #                Node(5, Node(6)),
    #                Node(6),
    #                Node(7, Node(8)),
    #                Node(8)]
    node_list_2 = [Node(i) for i in range(0, n+1)] 
    # transition_list_2 = [
    #     Transition(node_list_2[1], Activity("Task1", 2), node_list_2[2]),
    #     Transition(node_list_2[2], Activity("Task2", 4), node_list_2[3]),
    #     Transition(node_list_2[3], Activity("Task3", 10), node_list_2[4]),
    #     Transition(node_list_2[4], Activity("Task4", 4), node_list_2[5]),
    #     Transition(node_list_2[4], Activity("Task5", 6), node_list_2[6]),
    #     Transition(node_list_2[4], Activity("Task6", 7), node_list_2[7]),
    #     Transition(node_list_2[5], Activity("Task7", 5), node_list_2[7]),
    #     Transition(node_list_2[7], Activity("Task8", 8), node_list_2[9]),
    #     Transition(node_list_2[9], Activity("Task9", 4), node_list_2[11]),
    #     Transition(node_list_2[9], Activity("Task10", 5), node_list_2[12]),
    #     Transition(node_list_2[11], Activity("Task11", 0), node_list_2[12]),
    #     Transition(node_list_2[12], Activity("Task11", 6), node_list_2[13]),
    #     Transition(node_list_2[6], Activity("Task11", 7), node_list_2[8]),
    #     Transition(node_list_2[8], Activity("Task11", 9), node_list_2[10]),
    #     Transition(node_list_2[10], Activity("Task11", 2), node_list_2[13]),
    #     Transition(node_list_2[5], Activity("Task11", 0), node_list_2[8]),
    # ]
    transition_list_2 = [
        Transition(node_list_2[1], Activity("Task1", 12), node_list_2[2]),
        Transition(node_list_2[1], Activity("Task2", 23), node_list_2[3]),
        Transition(node_list_2[2], Activity("Task3", 15), node_list_2[4]),
        Transition(node_list_2[3], Activity("Task4", 27), node_list_2[6]),
        Transition(node_list_2[4], Activity("Task5", 18), node_list_2[5]),
        Transition(node_list_2[5], Activity("Task6", 6), node_list_2[6]),
    ]
    @staticmethod
    def create_graph_with_parallels(n):
        graph = {}
        for transition in TestPert2.transition_list_2:
            if transition.from_node in graph.keys():
                graph[transition.from_node].append(transition)
            else:
                graph[transition.from_node] = [transition]
        graph[TestPert2.node_list_2[n]] = [] 
        return graph

def read():
    with open('HW1_Nofar_Pert_CPM.log') as f:
        print("log file content:")
        print(f.read())


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, filename='HW1_Nofar_Alfasi_Pert_CPM.log', filemode='w', format='%(name)s %(message)s')
    print(Project(TestPert2.create_graph_with_parallels(n)))
    unittest.main()



CRITICAL PATH:  (Node 1) -> <Task1, 12 weeks> -> (Node 2)[12, 12]-> <Task3, 15 weeks> -> (Node 4)[27, 27]-> <Task5, 18 weeks> -> (Node 5)[45, 45]-> <Task6, 6 weeks> -> (Node 6)[51, 51]

			    (Node 1) -> <Task2, 23 weeks> -> (Node 3)[23, 24]-> <Task4, 27 weeks> -> (Node 6)[51, 51]

Traceback (most recent call last):
  File "E:\Python3.7\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "E:\Python3.7\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "E:\Python3.7\lib\argparse.py", line 1915, in consume_optional
    raise ArgumentError(action, msg % explicit_arg)
argparse.ArgumentError: argument -f/--failfast: ignored explicit argument 'C:\\Users\\TRANAN~1\\AppData\\Local\\Temp\\tmp-18452O72D2wAJYulu.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python3.7\lib\site-packages\IPython\core\inte

usage: ipykernel_launcher.py [-h] [-v] [-q] [--locals] [-f] [-c] [-b]
                             [-k TESTNAMEPATTERNS]
                             [tests [tests ...]]
ipykernel_launcher.py: error: argument -f/--failfast: ignored explicit argument 'C:\\Users\\TRANAN~1\\AppData\\Local\\Temp\\tmp-18452O72D2wAJYulu.json'


TypeError: object of type 'NoneType' has no len()

# Tối ưu đa mục tiêu (min)

In [5]:
import numpy as np
sols_all = []
p = 2 # số biến
r = (p+1)/(p**2)
lda = np.zeros((p+1,p))
lda[0] = [1/p**2] + [r for i in range(0,p-1)]
tmp = r*np.ones(p)
for i in range(1,p):
    lda[i] = tmp
    lda[i][i] = 1/p**2
lda[p] = [1/p for i in range(0,p)]
print(lda)
from cvxopt import matrix, solvers
G = matrix([[-1., -1., -1.,0.], [1., -1., 0.,-1.]]) # hàng 1 là hệ số của x1 , hàng 2 là hệ số của x2,..., hàng n hệ số của xn
h = matrix([3., -3., 0., 0.]) # hệ số tự do
A = np.array([[1,2],[0.,-2.]]) # hệ số các hàm mục tiêu
for i in range(lda.shape[1]+1):
    c = matrix(lda[i]@A)
    solvers.options['show_progress'] = False
    sol = solvers.lp(c, G, h)
    sols_all.append(np.array(sol['x']))
np.array(sols_all)


[[0.25 0.75]
 [0.75 0.25]
 [0.5  0.5 ]]


array([[[ 3.41538390e+00],
        [ 1.85384598e+00]],

       [[ 3.00000001e+00],
        [-1.45342492e-08]],

       [[ 1.79177494e-08],
        [ 3.00000002e+00]]])